start_message: "DEBUG: All hail the pitmaster, may your beef be grain fed and your pork tender."
time_format: '%I:%M%p' # '%H:%M' for 24 hours. Refer to https://docs.python.org/3.3/library/time.html?highlight=time.strftime#time.strftime
temperature_minimum_fahrenheit: 225
temperature_maximum_fahrenheit: 250
temperature_minimum_celsius: 107.22
temperature_maximum_celsius: 121.11
read_temperature_after_seconds: 5
send_mandatory_report_every_seconds: 300
indicate_led_for_seconds: 2
push_notification: 
  pushover: 
    abc: 123
  ntfy:
    topic: pitmaster
    servers: 
      - https://ntfy.sh
      # - http://0.0.0.0:30000
temperature_display_mode: # automatically calculated by your configuration, no need to provide. Will either resolve to 'celsius' or 'fahrenheit'
