apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    orgId: 1
    uid: prometheusss
    access: proxy 
    url: http://192.168.1.96:30020
    isDefault: true
    editable: true 
    jsonData: 
      httpMethod: POST